
#
# This LookML file was generated by AtScale on 2024-03-22T10:53:03.240169247Z
#
# AtScale engine version: 2023.4.1.12728
# AtScale DesignCenter version: 2023.4.1.21138
# AtScale version: 2023.4.1.6713
# Organization: default
# Project: MMSalesInsighrtsGBQ

connection: "atscale_mm_postgres"
label: "MMSalesInsighrtsGBQ"


include: "/views/MMSalesInsighrtsGBQ/InternetSalesCube.view.lkml"


explore: InternetSalesCube {
  label: "InternetSalesCube"
}

