
#
# This LookML file was generated by AtScale on 2024-03-22T10:25:06.753577541Z
#
# AtScale engine version: 2023.4.1.12728
# AtScale DesignCenter version: 2023.4.1.21138
# AtScale version: 2023.4.1.6713
# Organization: default
# Project: SalesInsighrts_GBQ_MM

connection: "atscalemm"
label: "SalesInsighrts_GBQ_MM"


include: "/views/SalesInsighrts__GBQ__MM/InternetSalesCube.view.lkml"


explore: InternetSalesCube {
  label: "InternetSalesCube"
}

