
#
# This LookML file was generated by AtScale on 2024-01-17T12:58:33.356006Z
#
# AtScale engine version: 2023.3.0.12548
# AtScale DesignCenter version: 2023.3.0.21049
# AtScale version: 2023.3.0.6477
# Organization: default
# Project: SalesInsighrts_GBQ_MM

connection: "atscalemm"
label: "SalesInsighrts_GBQ_MM"


include: "/views/SalesInsighrts__GBQ__MM/InternetSalesCube.view.lkml"


explore: InternetSalesCube {
  label: "InternetSalesCube"
}

