
#
# This LookML file was generated by AtScale on 2024-02-02T07:33:52.373488Z
#
# AtScale engine version: 2023.3.0.12548
# AtScale DesignCenter version: 2023.3.0.21049
# AtScale version: 2023.3.0.6477
# Organization: default
# Project: TPC-DS-10TB-Snowflake

connection: "atscalemm"
label: "TPC-DS-10TB-Snowflake"


include: "/views/TPC-DS-10TB-Snowflake/TPC-DS_Benchmark_Model_Snowflake.view.lkml"


explore: TPC_DS_Benchmark_Model_Snowflake {
  label: "TPC-DS Benchmark Model Snowflake"
}

